### ISSUE TITLE
Use ts-node instead of tsc

### ISSUE THREAD

**Issue by seriouslag** [VladimirMikulic/route-list#6] opened 2022-11-02 23:09 UTC
When the package is used on a typescript project the project is compiled and output-ed to a routelist folder.
I think a better user experience would be if there was no output and ts-node was used instead of TSC.

**Comment by VladimirMikulic** [comment] 2022-11-03 00:36
Thanks for the suggestion @seriouslag.
I'm wondering what do you consider "better user experience" by relying on ts-node.
`route-list` clears its output-ed folder automatically so developer/user of the CLI doesn't have to do anything.

**Comment by seriouslag** [comment] 2022-11-03 00:40
> Thanks for the suggestion @seriouslag. I'm wondering what do you consider "better user experience" by relying on ts-node. `route-list` clears its output-ed folder automatically so developer/user of the CLI doesn't have to do anything.

In my project it does not clear out automatically because of issues, any build issue and it seems to leave the folder.
The issue I am facing is that the compiled JS cannot resolve path references. I believe this would be fixed by using ts-node.

**Comment by VladimirMikulic** [comment] 2022-11-03 00:51
Interesting. Do you have a stack trace that you could possibly share or reproduction example?

**Comment by seriouslag** [comment] 2022-11-03 01:00
> Interesting. Do you have a stack trace that you could possibly share or reproduction example?

If I can get some free time I will most def create a repo, I don't see that happening for at least 2 weeks as my current project is not available to be shared :(

**Comment by VladimirMikulic** [comment] 2022-11-03 01:24
Ok, I guess I'll see you in 2 weeks then :)

**Comment by VladimirMikulic** [comment] 2022-11-21 19:44
@seriouslag any updates?

**Comment by VladimirMikulic** [comment] 2022-12-01 02:54
Closing due to lack of info.

**Closed as not planned by VladimirMikulic** 2022-12-01 02:54 UTC
